language: python
python:
  - '2.7'


install:
  - pip install --upgrade "pip<8"
  - pip --version
  - pip install -r requirements.txt


script:
  - ansible-lint playbooks/site.yml
  - ansible-lint playbooks/heat_deprovision.yml

